before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: evOVzu4ZiU3r31+IonWM/lxpNTOEC96n5JQIbbKwVvZaaYr6+Kfmb15NqmGvYhik6s0981s1dztHe7Fphh55rVE0/Aey3PvDaD04zswOHxPzu0uhGp+/f4Li8RPOxo+QSFVpy5iXjyBaiNELPMCGDwvazz0ZHgDSfW6Ol+zxbtAXYvD31lGOBjT73tAogVVuXI8P06k559UKK6W1bqOxfu3l3as9rWimfDGd3pPbP8VkKO9qS3SZBOqwE3YAc49upPjSp/fHTunmKP7MAnukBjxbspjLvh/agaJ22bi+Koq/wZJ+Y9Ca7FL5is/SvTBiOh1XXEuRwrKvyuTlWb1FqHWyZ7sPetKn+R3pB27spnJq7pTpPBxou3bh4/8C1caoqOzj0s66wOR3H4hWOZj3EfVRdgsAUhDgkrpKPE7lS5SDla5NUX5c5F+cB06gk76dnUUX2AE6wzrRFk/9KP/SlOlrfKfz21fNbXUDxUGiz5+rsnelUPi/YxFhtvuKgkICFJ9tH1r6dlL1fDq6ME6IJ/qPSjWLF86bstBpMF9jSrsEEEnUernyqGhMYkmMTR/qKu0Fd0Cz3OhO1g0fn2WgP2N5EATFXz951oQGjebSAvqFVVarIWxsG3cT5MADh9lmy4/2icT7JMpyCAoLOyos6uTfbkqAY11rO3ZiehDmRaw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
